use crate::{db::{dissolve, query, query_value}, AppData};
use actix_web::{web::{Form, Data}, Responder, get, post, HttpResponse, HttpRequest, http::header::q};
use super::sites::{POST, TASK};
use chrono::{DateTime, Utc};

#[derive(serde::Deserialize)]
struct JobData{
    title: String,
    body: String,
    time: String, 
    price: f32,
    location: String,
}


#[derive(serde::Deserialize, serde::Serialize, Debug)]
pub struct Job{
    title: String,
    body: String,
    // location: Location, todo!()
    time: DateTime<Utc>,
    price: crate::structs::Money, 
    username: String,
    location: String,
}
impl Job{
    pub fn new(username: String, title: String, body: String, time: DateTime<Utc>, price: crate::structs::Money, location: String) -> Job{
        Job { username, title, body, time, price, location}
    }
}

#[get("/post-job")]
pub async fn post() -> impl Responder{
    HttpResponse::Ok().body(POST)
}

#[post("/post-job")]
async fn post_job(form: Form<JobData>, req: HttpRequest, data: Data<AppData>) -> impl Responder{

    let cookie: String = req.cookie("login").map(|c|{c.value().to_string()}).unwrap_or("false;0".into());
    let (cookie, username) = cookie.split_once(';').unwrap_or(("false", "0"));
    let cookie = cookie.parse().unwrap_or(false);
    if !cookie{
        return HttpResponse::Forbidden().body("Cannot access contents; log in.")
    }
    
    let JobData { title, body, time, price, location } = form.0;

    use chrono::TimeZone;
    //https://github.com/kelvins/US-Cities-Database
    let mut iter = time.split('-');
    let year = iter.next().unwrap().parse().unwrap();
    let month = iter.next().unwrap().parse().unwrap();
    let day = iter.next().unwrap().parse().unwrap();
    let time = Utc.with_ymd_and_hms(year, month, day, 0, 0, 0).single().ok_or("REGISTER JOB FN: Invalid Date.").unwrap();
    //time is written in the format: yyyy-mm-dd

    let job = Job::new(username.to_string(), title, body, time, crate::structs::Money(price), location);

    let mut db = data.db.lock().await;
    dissolve(query_value(&mut db, "CREATE jobs SET data = $job", Some(("job", job))).await, 1);


    // todo!();
    HttpResponse::Ok().body(POST)
}

#[get("/jobs/{id}")]
pub async fn jobs(id: actix_web::web::Path<String>, data: Data<AppData>,) -> impl Responder{
    //get job by id -> link should be generated by backend and then given to the frontend when the job is posted
    let res2 = query::<Job>(&mut *data.db.lock().await, r#"SELECT type::thing("jobs", $id) FROM jobs;"#, Some(("id", id.as_str()))).await.unwrap();
    let res1 = res2.get(0).unwrap().as_ref().unwrap();
    let result = res1;
    let len = result.len();
    //there should never be more than one but just in case
    if len != 1 {
        //bad request 
    }
    let job = result.get(0).unwrap();
    //give job to frontend etc. etc. etc.
    todo!() as HttpResponse
}
#[derive(serde::Serialize, serde::Deserialize)]
struct Address{
    location: String,
}

#[actix_web::get("/tasks")]
pub async fn tasks() -> impl Responder{
    HttpResponse::Ok().body(TASK)
}

#[post("/tasks")]
async fn tasks_in_area(app_data: Data<AppData>, form: Form<Address>) -> impl Responder{
    
    // in the future allow filtering of multiple addresses.
    let address = form.into_inner().location;
    let res2 = query::<Job>(&mut *app_data.db.lock().await, "SELECT VALUE data FROM jobs WHERE data.location = type::string($location);", Some(("location", address))).await.unwrap();
    let result = res2.get(0).unwrap().as_ref().unwrap();
    //give vector of jobs to frontend
    HttpResponse::Ok().body(super::sites::TASK)
}

//new model idea: have two types of functions, ones to call from js, and others to occur when you go to a certain page. They shouldn't have much overlap? IDK . WE CAN DO THISSSSSSSSSS