use crate::{db::{query, query_value}, AppData};
use actix_identity::Identity;
use actix_web::{web::{Form, Data, self}, Responder, get, post, HttpResponse, HttpRequest};
use surrealdb::sql::Thing;
use super::sites::{POST, TASK};
use chrono::{DateTime, Utc};
use super::signup::{AccountState, login_user, retrieve_user};

#[derive(serde::Deserialize, serde::Serialize, Debug)]
pub struct JobData{
    title: String,
    body: String,
    time: String, 
    price: f32,
    location: String,
}


#[derive(serde::Deserialize, serde::Serialize, Debug)]
pub struct Job{
    title: String,
    body: String,
    // location: Location, todo!()
    time: DateTime<Utc>,
    // price: crate::structs::Money,
    price: u64, 
    // username: String, left in favor for the record link on user
    location: String,
}
impl Job{
    pub fn new(title: String, body: String, time: DateTime<Utc>, price: u64, location: String) -> Job{
        Job { title, body, time, price, location}
    }
}

#[get("/post-job")]
pub async fn post() -> impl Responder{
    HttpResponse::Ok().body(POST)
}

#[post("/post-job-2")]
pub async fn post_job(form: web::Form<JobData>, data: Data<AppData>, identity: Option<Identity>) -> impl Responder{
    // let user = request.get_identity();
    // let username = user.unwrap().id().unwrap();
    //ditch actix-identity and now use pure actix-session
    let username = retrieve_user(identity.unwrap()).unwrap();
    
    let JobData { title, body, time, price, location } = form.into_inner();

    use chrono::TimeZone;
    //https://github.com/kelvins/US-Cities-Database
    let mut iter = time.split('-');
    let year = iter.next().unwrap().parse().unwrap();
    let month = iter.next().unwrap().parse().unwrap();
    let day = iter.next().unwrap().parse().unwrap();
    let time = Utc.with_ymd_and_hms(year, month, day, 0, 0, 0).single().ok_or("REGISTER JOB FN: Invalid Date.").unwrap();
    //time is written in the format: yyyy-mm-dd

    let job = Job::new(title, body, time, (price * 100.0) as u64, location);

    let surrealql = 
    r#"
    BEGIN TRANSACTION;
        LET $id = (SELECT id FROM accounts WHERE username=type::string($username))[0].id;
        CREATE jobs SET data = $job, user = type::thing("accounts", $id);
    COMMIT TRANSACTION;"#;
    //^feh PLEASE MAKE SURE TO ERROR HANDLE WHAT HAPPENS IF THERE ARE NO ACCOUNTS WITH THAT USERNA<E
    let mut db = data.db.lock().await;
    query_value(&mut db, surrealql, Some(JobUsername{ job, username })).await.unwrap();

    
    HttpResponse::SeeOther().append_header((actix_web::http::header::LOCATION, "/post-job")).body(POST)
}

#[derive(serde::Serialize)]
struct JobUsername{
    job: Job,
    username: String,
}



#[get("/jobs/{id}")]
pub async fn jobs(_: actix_web::web::Path<String>) -> impl Responder{
    //which way is better using `id` or using post? 
    HttpResponse::Ok().body(crate::sites::JOBS)
}
// #[post("/jobs_attain")]
// pub async fn jobs_data(data: Data<AppData>) -> impl Responder{
//     //get job by id -> link should be generated by backend and then given to the frontend when the job is posted
//     let res2 = query::<Job>(&mut *data.db.lock().await, r#"SELECT type::thing("jobs", $id) FROM jobs;"#, Some(("id", id.as_str()))).await.unwrap();
//     let res1 = res2.get(0).unwrap().as_ref().unwrap();
//     let result = res1;
//     let len = result.len();
//     //there should never be more than one but just in case
//     if len != 1 {
//         //bad request 
//     }
//     let job = result.get(0).unwrap();
//     HttpResponse::Ok().content_type("application/json").json(settings_data)
// }






#[derive(serde::Serialize, serde::Deserialize)]
struct Address{
    location: String,
}

#[actix_web::get("/tasks")]
pub async fn tasks() -> impl Responder{
    HttpResponse::Ok().body(TASK)
}

// #[actix_web::route("/job-handling", method="GET", method="POST")]
#[actix_web::post("/job-handling")]
pub async fn tasks_in_area(app_data: Data<AppData>, js: web::Json<String>) -> impl Responder{
    
    // in the future allow filtering of multiple addresses.
    let address = js.into_inner();
    let mut res2 = query::<JobPost>(&mut *app_data.db.lock().await, "SELECT * FROM jobs WHERE data.location = type::string($location) FETCH user.accounts;", Some(("location", address))).await.unwrap();
    let result: Vec<_> = res2.get_mut(0).unwrap().as_mut().unwrap().iter_mut().map(|a|{
        a.timestamp_converted().unwrap();
        a
    }).collect();
    // println!("{result:?}");
    HttpResponse::Ok().content_type("application/json").json(result)
}

#[derive(serde::Serialize, serde::Deserialize, Debug)]
struct JobPost{
    id: Thing,
    
    data: JobData,

    user: JobRecordLink,
}
impl JobPost{
    fn timestamp_converted(&mut self) -> Result<(), Box<dyn std::error::Error>>{
        self.data.time = convert_timestamp(&self.data.time)?;
        Ok(())
    }
}



#[derive(serde::Serialize, serde::Deserialize, Debug)]
struct JobRecordLink{
    displayname: String,
    username: String,
    state: AccountState,
}

//new model idea: have two types of functions, ones to call from js, and others to occur when you go to a certain page. They shouldn't have much overlap? IDK . WE CAN DO THISSSSSSSSSS

pub fn convert_timestamp(timestamp: &str) -> Result<String, Box<dyn std::error::Error>> {
    println!("{timestamp}");
    let datetime = DateTime::parse_from_rfc3339(timestamp)?.with_timezone(&Utc);
    Ok(datetime.format("%m/%d/%Y").to_string())
}