use crate::{db::{query, query_value}, AppData};
use actix_web::{web::{Form, Data, self}, Responder, get, post, HttpResponse, HttpRequest};
use super::sites::{POST, TASK};
use chrono::{DateTime, Utc};
use actix_session::Session;
use super::signup::{Account, login_user, retrieve_user};

#[derive(serde::Deserialize)]
pub struct JobData{
    title: String,
    body: String,
    time: String, 
    price: f32,
    location: String,
}


#[derive(serde::Deserialize, serde::Serialize, Debug)]
pub struct Job{
    title: String,
    body: String,
    // location: Location, todo!()
    time: DateTime<Utc>,
    price: crate::structs::Money, 
    username: String,
    location: String,
}
impl Job{
    pub fn new(username: String, title: String, body: String, time: DateTime<Utc>, price: crate::structs::Money, location: String) -> Job{
        Job { username, title, body, time, price, location}
    }
}

#[get("/post-job")]
pub async fn post() -> impl Responder{
    HttpResponse::Ok().body(POST)
}

#[post("/post-job-2")]
pub async fn post_job(form: web::Form<JobData>, data: Data<AppData>, session: Session) -> impl Responder{
    // let user = request.get_identity();
    // let username = user.unwrap().id().unwrap();
    //ditch actix-identity and now use pure actix-session
    let username = retrieve_user(session).unwrap().unwrap();
    
    let JobData { title, body, time, price, location } = form.into_inner();

    use chrono::TimeZone;
    //https://github.com/kelvins/US-Cities-Database
    let mut iter = time.split('-');
    let year = iter.next().unwrap().parse().unwrap();
    let month = iter.next().unwrap().parse().unwrap();
    let day = iter.next().unwrap().parse().unwrap();
    let time = Utc.with_ymd_and_hms(year, month, day, 0, 0, 0).single().ok_or("REGISTER JOB FN: Invalid Date.").unwrap();
    //time is written in the format: yyyy-mm-dd

    let job = Job::new(username.to_string(), title, body, time, crate::structs::Money(price), location);

    let mut db = data.db.lock().await;
    query_value(&mut db, "CREATE jobs SET data = $job", Some(("job", job))).await.unwrap();


    // todo!();
    HttpResponse::Ok().body(POST)
}






#[get("/jobs/{id}")]
pub async fn jobs(id: actix_web::web::Path<String>, data: Data<AppData>,) -> impl Responder{
    //get job by id -> link should be generated by backend and then given to the frontend when the job is posted
    let res2 = query::<Job>(&mut *data.db.lock().await, r#"SELECT type::thing("jobs", $id) FROM jobs;"#, Some(("id", id.as_str()))).await.unwrap();
    let res1 = res2.get(0).unwrap().as_ref().unwrap();
    let result = res1;
    let len = result.len();
    //there should never be more than one but just in case
    if len != 1 {
        //bad request 
    }
    let job = result.get(0).unwrap();
    //give job to frontend etc. etc. etc.
    todo!() as HttpResponse
}
#[derive(serde::Serialize, serde::Deserialize)]
struct Address{
    location: String,
}

#[actix_web::get("/tasks")]
pub async fn tasks() -> impl Responder{
    HttpResponse::Ok().body(TASK)
}

// #[actix_web::route("/job-handling", method="GET", method="POST")]
#[actix_web::post("/job-handling")]
pub async fn tasks_in_area(app_data: Data<AppData>, js: web::Json<String>) -> impl Responder{
    
    // in the future allow filtering of multiple addresses.
    let address = js.into_inner();
    let res2 = query::<JobPost>(&mut *app_data.db.lock().await, "SELECT VALUE data FROM jobs WHERE data.location = type::string($location);", Some(("location", address))).await.unwrap();
    let result = res2.get(0).unwrap().as_ref().unwrap();
    // println!("{result:?}");
    HttpResponse::Ok().content_type("application/json").json(result)
}

#[derive(serde::Serialize, serde::Deserialize, Debug)]
struct JobPost{
    id: String,
    time: String,

    title: String,
    body: String,
    price: f32,

    user: JobRecordLink,
}

#[derive(serde::Serialize, serde::Deserialize, Debug)]
struct JobRecordLink{
    displayname: String,
    username: String,
}

// ISSUE WITH TAS: 1. Undefineds
//new model idea: have two types of functions, ones to call from js, and others to occur when you go to a certain page. They shouldn't have much overlap? IDK . WE CAN DO THISSSSSSSSSS
